### ISSUE TITLE
externFun not work

### ISSUE THREAD

**Issue by yuchangyuan** [Copilot-Language/copilot-c99#12]
Below code with 'externFun' not work

```
{-# LANGUAGE ScopedTypeVariables #-}
module Main where

import qualified Prelude as P
import Copilot.Language

import Copilot.Compile.C99
import Copilot.Language.Reify

import Data.Char(ord)


sensor1 = externFun "sensor1" [] $ Just $ constB True

spec = do
  trigger "trig" (constB True) [arg sensor1]

main = do
     putStrLn ""
     prettyPrint spec
     putStrLn "\n\n"
     reify spec >>= compile "copilot"
```

Output message as below
```

trigger "trig" = true [
  arg Extf_sensor1()
  ]


a.hs: src/Copilot/Compile/C99/CodeGen.hs:(130,15)-(139,81): Non-exhaustive patterns in case

```

**Comment by fdedden** [comment]
externFun (among some other things like observers) are deprecated in the current version of Copilot. They do not add any functionality to Copilot that could not be expressed in any other way.

Removing these constructs will break the interface, and thus will have to wait for the 3.1 release of Copilot, which will happen after we implemented some of our other plans as well.

**Comment by yuchangyuan** [comment]
With externFun, there can be more code in Haskell side and less code in C side(glue code), less glue code means less chance to get thing wrong. 

But it's true that all code use externFun can port to current version of Copilot.

**Comment by fdedden** [comment]
The main reason we want to remove externFun is that it introduces possible side-effects to a stream in Copilot. With them removed, only triggers can cause side-effects, keeping the 'dangerous' part in one place.
