### ISSUE TITLE
Label not implemented

### ISSUE THREAD

**Issue by ivanperez-nfm** [Copilot-Language/copilot-c99#14]
Label is currently not implemented, which makes one of our use cases crash.

**Comment by ivanperez-nfm** [comment]
(I will send a PR for this.)

**Comment by ivanperez-nfm** [comment]
Just for documentation: with my fix, the following code breaks:

```haskell
module Main (main) where
  
import Prelude hiding ((>), (<), (&&), (||), (<=), (>=), (/=), div)
import Language.Copilot
import Copilot.Compile.C99

extB :: Stream Bool
extB = extern "latO" Nothing

lblB :: Stream Bool
lblB = label "?x" extB

spec :: Spec
spec = do
  trigger "someTrigger" lblB []

main = do
  reify spec >>= compile "sphericalwcv2"
```

with the following C code:

```C
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include "sphericalwcv2.h"

bool someTrigger_guard(void) {
  return latO_cpy;
}

void step(void) {
  if ((someTrigger_guard)()) {
    (someTrigger)();
  };
}
```

and the following error:

```bash
$ llvm-gcc -c sphericalwcv2.c 
sphericalwcv2.c:8:10: error: use of undeclared identifier 'latO_cpy'
  return latO_cpy;
         ^
1 error generated.
```

**Comment by ivanperez-nfm** [comment]
Is this implementation of `transexpr` correct, and where is that variable defined?

```haskell
transexpr (ExternVar _ name _) = return $ C.Ident (excpyname name)
```

**Comment by ivanperez-keera** [comment]
@fdedden Could you please take a look? This looks suspiciously simple.

**Comment by fdedden** [comment]
I have added the case for Label in the `gatherexts` function. The purpose of this function is to gather all external variables to aid in making copies of them. This solved your issue. I did some quick tests, you can close the issue if you agree it works correctly now.

**Comment by ivanperez-keera** [comment]
I must be missing something. I just tried the code above and it still generates broken C for me. Does it work for you?
